//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.TICKETs = new HashSet<TICKET>();
        }
    
        public long EMPLOYEEID { get; set; }
        public string ELASTNAME { get; set; }
        public string EFIRSTNAME { get; set; }
        public string EEMAIL { get; set; }
        public string EPHONE { get; set; }
        public string EPASSWORD { get; set; }
        public System.DateTime EDOB { get; set; }
        public string EADDRESS { get; set; }
        public System.DateTime EDATEOFWORK { get; set; }
        public string ROLENAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKETs { get; set; }
    }
}
