//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyCinema.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GalaxyCinemaEntities : DbContext
    {
        public GalaxyCinemaEntities()
            : base("name=GalaxyCinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTOR> ACTORs { get; set; }
        public virtual DbSet<AGERATING> AGERATINGs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<DAYCAT> DAYCATs { get; set; }
        public virtual DbSet<DIRECTOR> DIRECTORs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<GENRE> GENREs { get; set; }
        public virtual DbSet<MOVIE> MOVIEs { get; set; }
        public virtual DbSet<NATION> NATIONs { get; set; }
        public virtual DbSet<PARAMETER> PARAMETERs { get; set; }
        public virtual DbSet<PAYMENT> PAYMENTs { get; set; }
        public virtual DbSet<REVIEW> REVIEWs { get; set; }
        public virtual DbSet<SEAT> SEATs { get; set; }
        public virtual DbSet<SHOWTIME> SHOWTIMEs { get; set; }
        public virtual DbSet<THEATER> THEATERs { get; set; }
        public virtual DbSet<TICKET> TICKETs { get; set; }
        public virtual DbSet<TICKETDETAIL> TICKETDETAILs { get; set; }
        public virtual DbSet<TICKETPRICE> TICKETPRICEs { get; set; }
        public virtual DbSet<TICKETSEAT> TICKETSEATs { get; set; }
        public virtual DbSet<TICKETTYPE> TICKETTYPEs { get; set; }
    }
}
