//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVIE()
        {
            this.REVIEWs = new HashSet<REVIEW>();
            this.SHOWTIMEs = new HashSet<SHOWTIME>();
            this.ACTORs = new HashSet<ACTOR>();
            this.GENREs = new HashSet<GENRE>();
        }
    
        public long MOVIEID { get; set; }
        public long DIRECTORID { get; set; }
        public int NATIONID { get; set; }
        public int AGEID { get; set; }
        public string MOVIENAME { get; set; }
        public int DURATION { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime RELEASEDATE { get; set; }
        public string MOVIESTATUS { get; set; }
        public string POSTER { get; set; }
    
        public virtual AGERATING AGERATING { get; set; }
        public virtual DIRECTOR DIRECTOR { get; set; }
        public virtual NATION NATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEW> REVIEWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHOWTIME> SHOWTIMEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTOR> ACTORs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENRE> GENREs { get; set; }
    }
}
