//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETER
    {
        public long PARAMETERID { get; set; }
        public string PARAMETERDESCRIPTION { get; set; }
        public string VALUE { get; set; }
        public string UNITOFMEASUREMENT { get; set; }
        public bool APPLYCATION { get; set; }
    }
}
