//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEAT()
        {
            this.TICKETSEATs = new HashSet<TICKETSEAT>();
        }
    
        public long SEATID { get; set; }
        public long THEATERID { get; set; }
        public string SEATNAME { get; set; }
    
        public virtual THEATER THEATER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKETSEAT> TICKETSEATs { get; set; }
    }
}
