//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TICKET()
        {
            this.TICKETDETAILs = new HashSet<TICKETDETAIL>();
        }
    
        public int TICKETID { get; set; }
        public long PAYMENTID { get; set; }
        public Nullable<long> CUSTOMERID { get; set; }
        public long SHOWTIMEID { get; set; }
        public long EMPLOYEEID { get; set; }
        public int TOTALTICKETS { get; set; }
        public decimal TOTALAMOUT { get; set; }
        public bool TICKETSTATUS { get; set; }
        public System.DateTime SELLDATE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual SHOWTIME SHOWTIME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKETDETAIL> TICKETDETAILs { get; set; }
    }
}
