//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETPRICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TICKETPRICE()
        {
            this.TICKETDETAILs = new HashSet<TICKETDETAIL>();
        }
    
        public int TICKETPRICEID { get; set; }
        public int TICKETTYPEID { get; set; }
        public int DAYCATID { get; set; }
        public decimal PRICETTICKET { get; set; }
    
        public virtual DAYCAT DAYCAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKETDETAIL> TICKETDETAILs { get; set; }
        public virtual TICKETTYPE TICKETTYPE { get; set; }
    }
}
