//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETSEAT
    {
        public long TICKETSEATID { get; set; }
        public long TICKETDETAILID { get; set; }
        public long SEATID { get; set; }
    
        public virtual SEAT SEAT { get; set; }
        public virtual TICKETDETAIL TICKETDETAIL { get; set; }
    }
}
